import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import stylesLayout from '@/styles/Layout.module.scss'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Splash Test</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={stylesLayout.main}>
        <div>Foo</div>
        <div>Foo2</div>
        <div>Foo3</div>
        <div>Foo4</div>
      </main>
    </>
  )
}
